tabs:
  -
    elements:
      -
        fieldUid: 84b801b8-940b-4cee-b604-71342dea325d
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: f1497bca-02b2-4c0d-b9b6-1a18b4d49cf7 # bio
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
    name: UserInfo
    sortOrder: 1
