defaultPlacement: end
enableVersioning: true
handle: blogpost
name: blogpost
propagationMethod: all
siteSettings:
  341c12ec-dfad-49a9-a1d0-8a10df36b6df: # Inlog
    enabledByDefault: true
    hasUrls: true
    template: blogpost/_entry
    uriFormat: 'blogpost/{slug}'
type: channel
